Vagrant.require_version ">= 1.8.0"

Vagrant.configure(2) do |config|

  # Set VM parameters
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  linux_servers = {
    "ubuntu-focal" => {:box => "ubuntu/focal64"},
    "ubuntu-bionic" => {:box => "ubuntu/bionic64"},
    "debian-buster" => {:box => "debian/buster64"},
    "fedora-32" => {:box => "fedora/32-cloud-base"},
    "centos-8" => {:box => "centos/8"},
    "centos-7" => {:box => "centos/7"},
    "arch-current" => {:box => "archlinux/archlinux"},
    "leap-15-2" => {:box => "opensuse/Leap-15.2.x86_64"}
  }

  linux_servers.each do |hostname, info|
    config.vm.define hostname do |cfg|  # a define per hostname
      cfg.vm.box = info[:box]
      cfg.vm.hostname = hostname
    end
  end

  config.vm.define "freebsd-11" do |freebsd_11|
    freebsd_11.vm.box = "freebsd/FreeBSD-11.4-STABLE"
    # Custom parameters for a FreeBSD guest using the official box
    freebsd_11.vm.guest = :freebsd
    freebsd_11.vm.hostname = "freebsd-11"
    freebsd_11.vm.base_mac = "080027D14C66"
    freebsd_11.ssh.shell = "sh"
    # Additional parameters for VirtualBox, needed to make FreeBSD work
    freebsd_11.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end
  config.vm.define "freebsd-12" do |freebsd_12|
    freebsd_12.vm.box = "freebsd/FreeBSD-12.1-STABLE"
    # Custom parameters for a FreeBSD guest using the official box
    freebsd_12.vm.guest = :freebsd
    freebsd_12.vm.hostname = "freebsd-12"
    freebsd_12.vm.base_mac = "080027D14C66"
    freebsd_12.ssh.shell = "sh"
    # Additional parameters for VirtualBox, needed to make FreeBSD work
    freebsd_12.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    end
  end


  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "test.yml"
    ansible.raw_arguments = "--diff"

    ansible.groups = {
      "ubuntu" => ["ubuntu-focal", "ubuntu-bionic"],
      "debian" => ["debian-buster"],
      "fedora" => ["fedora-32"],
      "fedora:vars" => {
        "ansible_python_interpreter" => "/usr/bin/python3"
      },
      "centos" => ["centos-8", "centos-7"],
      "arch" => ["arch-current"],
      "opensuse" => ["leap-15-2"],
      "freebsd" => ["freebsd-11", "freebsd-12"]
    }

    ansible.host_vars = {

    }
  end
end

